const C=document.getElementById('content'),S=document.getElementById('status'),RT=document.getElementById('root-tree'),T=document.getElementById('index-tree'),SS=document.getElementById('system-section'),ST=document.getElementById('system-tree'),TR=document.getElementById('target-root'),SR=document.getElementById('system-root');let currentPath=null,rootTree=null,indexTree=null,systemTree=null;const rootCollapsedPaths=new Set(),projectCollapsedPaths=new Set(),systemCollapsedPaths=new Set();
function ready(fn){if(typeof marked!=='undefined'&&marked){fn()}else setTimeout(()=>ready(fn),50)}
function showStatus(msg,duration){S.textContent=msg;S.classList.remove('hidden');clearTimeout(S._timer);if(duration)S._timer=setTimeout(()=>S.classList.add('hidden'),duration)}
function escapeHtml(t){const e=document.createElement('div');e.textContent=t;return e.innerHTML}
function navigateTo(path,pushState){
 if(path===currentPath)return;currentPath=path;loadFile(path);updateActiveNav();
 if(pushState!==false){const url='/view?path='+encodeURIComponent(path);history.pushState({path},'',url)}
}
async function loadFile(path){
 try{const r=await fetch('/api/file?path='+encodeURIComponent(path));if(!r.ok)throw new Error('HTTP '+r.status);const t=await r.text(),h=marked.parse(t);C.innerHTML=h;showStatus('Loaded: '+path,2000);C.querySelectorAll('a[href]').forEach(anchorHandler)}
 catch(e){C.innerHTML='<p style="color:red">Error loading <code>'+escapeHtml(path)+'</code>: '+escapeHtml(e.message)+'</p>'}
}
function anchorHandler(a){const h=a.getAttribute('href');if(!h)return;if(h.startsWith('http://')||h.startsWith('https://')||h.startsWith('mailto:')||h.startsWith('#'))return;if(h.endsWith('.md')){a.addEventListener('click',e=>{e.preventDefault();navigateTo(resolvePath(currentPath||'',h))})}}
function resolvePath(base,target){if(base.startsWith('system:')){const innerBase=base.slice(7),innerTarget=target.startsWith('/')?target.slice(1):target;return 'system:'+resolveRelativePath(innerBase,innerTarget)}if(target.startsWith('/'))return target.slice(1);return resolveRelativePath(base,target)}
function resolveRelativePath(base,target){const parts=base.split('/').slice(0,-1).concat(target.split('/')),result=[];for(const p of parts){if(p==='.'||p==='')continue;if(p==='..'){result.pop();continue}result.push(p)}return result.join('/')}
window.addEventListener('popstate',e=>{const p=new URLSearchParams(location.search).get('path')||(e.state&&e.state.path)||null;if(p)navigateTo(p,false);else navigateTo('.adaptive-agents/INDEX.md',false)})
async function loadRootTree(){try{const r=await fetch('/api/tree');if(!r.ok)throw new Error('HTTP '+r.status);rootTree=await r.json();rootCollapsedPaths.clear();renderTree(RT,rootTree,rootCollapsedPaths,renderRootTree)}catch(e){RT.innerHTML='<p style="font-size:13px;color:#a33">Project repo unavailable</p>'}}
async function loadIndexTree(){try{const r=await fetch('/api/index-tree');if(!r.ok)throw new Error('HTTP '+r.status);indexTree=await r.json();projectCollapsedPaths.clear();renderTree(T,indexTree,projectCollapsedPaths,renderIndexTree)}catch(e){T.innerHTML='<p style="font-size:13px;color:#a33">Navigation unavailable</p>'}}
async function loadSystemTree(){try{const r=await fetch('/api/system-index-tree');if(!r.ok)throw new Error('HTTP '+r.status);systemTree=await r.json();systemCollapsedPaths.clear();SS.hidden=false;renderTree(ST,systemTree,systemCollapsedPaths,renderSystemTree)}catch(e){systemTree=null;SS.hidden=true;ST.innerHTML=''}}
async function loadContext(){try{const r=await fetch('/api/context');if(!r.ok)throw new Error('HTTP '+r.status);const c=await r.json();TR.textContent=c.targetName+' — '+c.targetRoot;TR.title=c.targetRoot;SR.textContent=c.systemName+' — '+c.systemHome;SR.title=c.systemHome;document.title='Adaptive Agents — '+c.targetName}catch(e){TR.textContent='Context unavailable';SR.textContent='Context unavailable'}}
function renderRootTree(){if(rootTree)renderTree(RT,rootTree,rootCollapsedPaths,renderRootTree)}
function renderIndexTree(){if(indexTree)renderTree(T,indexTree,projectCollapsedPaths,renderIndexTree)}
function renderSystemTree(){if(systemTree)renderTree(ST,systemTree,systemCollapsedPaths,renderSystemTree)}
function renderTree(container,tree,collapsedSet,rerender){container.innerHTML='';container.appendChild(renderNodeList([tree],0,collapsedSet,rerender));updateActiveNav()}
function renderNodeList(nodes,depth,collapsedSet,rerender){const ul=document.createElement('ul');for(const node of nodes){const subItems=[].concat(node.children||[],node.links||[]),hasSubContent=subItems.length>0,li=document.createElement('li'),row=document.createElement('div'),button=document.createElement('button'),label=node.path?document.createElement('a'):document.createElement('span');row.className='tree-row';button.type='button';button.dataset.path=node.path||node.name;if(hasSubContent){const key=node.path||node.name,defaultCollapsed=depth>0,isCollapsed=collapsedSet.has(key)?!defaultCollapsed:defaultCollapsed;li.classList.toggle('collapsed',isCollapsed);button.textContent=isCollapsed?'▸':'▾';button.setAttribute('aria-label',(isCollapsed?'Expand ':'Collapse ')+node.name);button.setAttribute('aria-expanded',String(!isCollapsed));button.addEventListener('click',()=>{if(collapsedSet.has(key))collapsedSet.delete(key);else collapsedSet.add(key);rerender()})}else{button.className='empty';button.textContent='';button.setAttribute('aria-hidden','true');button.tabIndex=-1}label.textContent=node.name;if(node.path){label.href='/view?path='+encodeURIComponent(node.path);label.dataset.path=node.path;label.addEventListener('click',e=>{e.preventDefault();navigateTo(node.path)})}else{label.className='node-label'}row.appendChild(button);row.appendChild(label);li.appendChild(row);if(hasSubContent)li.appendChild(renderNodeList(subItems,depth+1,collapsedSet,rerender));ul.appendChild(li)}return ul}
function updateActiveNav(){const all=[RT,T,ST];for(const el of all)if(el)el.querySelectorAll('a').forEach(a=>a.classList.toggle('active',a.dataset.path===currentPath))}
function connectSSE(){const s=new EventSource('/events');s.addEventListener('file_changed',e=>{const d=JSON.parse(e.data);if(d.path===currentPath)loadFile(currentPath)});s.addEventListener('file_added',e=>{const d=JSON.parse(e.data);if(d.path===currentPath)loadFile(currentPath);showStatus('File added: '+d.path,3000)});s.addEventListener('file_removed',e=>{const d=JSON.parse(e.data);if(d.path===currentPath)navigateTo('.adaptive-agents/INDEX.md',false);showStatus('File removed: '+d.path,3000)});s.addEventListener('tree_changed',()=>{loadRootTree();loadIndexTree();loadSystemTree()});s.onerror=()=>showStatus('SSE reconnecting...',3000)}
ready(()=>{marked.use({breaks:true,gfm:true});connectSSE();loadContext();loadRootTree();loadIndexTree();loadSystemTree();const ip=new URLSearchParams(location.search).get('path');if(ip)navigateTo(ip,false);else navigateTo('.adaptive-agents/INDEX.md',false)})
