#!/usr/bin/env bash
set -euo pipefail

# install-opencode.sh
#
# Installs Adaptive Agents user-wide guidance for OpenCode.
#
# Architecture (two parts, user scope — see .adaptive-agents/planning):
#   1. Single entry point: one `instructions` entry in the OpenCode global
#      config loading the canonical repository AGENTS.md content at session
#      start. AGENTS.md -> INDEX.md -> instructions/ fan-out handles routing.
#   2. Trusted source directories: a `permission.external_directory` grant
#      marking the repository safe to read and write from sessions rooted
#      elsewhere (OpenCode gates external paths behind "ask" by default).
#
# Official documentation (verified 2026-07-11, OpenCode v1.14.22):
#   https://opencode.ai/docs/config/       — global config, instructions field
#   https://opencode.ai/docs/rules/        — AGENTS.md loading, no import syntax
#   https://opencode.ai/docs/permissions/  — external_directory permission
#
# This script also migrates away prior-generation artifacts:
#   - the sentinel-duplicating global AGENTS.md copy
#   - redundant `instructions` entries (INDEX.md, global.instructions.md, glob)
#   - installed slash-command files
#   - stale %APPDATA%/opencode artifacts (never consumed by OpenCode)
#
# It does not:
#   - copy or generate guidance content (the repository is the source of truth)
#   - modify provider, model, or unrelated permission configuration
#   - modify project repositories
#   - store secrets

usage() {
  cat <<EOF
Usage:
  ./scripts/install-opencode.sh [options]

Options:
  --dry-run              Show what would change without writing files.
  --opencode-config PATH Use an explicit OpenCode config file path.
  -h, --help             Show this help.

Examples:
  ./scripts/install-opencode.sh
  ./scripts/install-opencode.sh --dry-run
  ./scripts/install-opencode.sh --opencode-config ~/custom-opencode.json
EOF
}

DRY_RUN=0
EXPLICIT_CONFIG_PATH=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --opencode-config)
      EXPLICIT_CONFIG_PATH="${2:-}"
      if [[ -z "$EXPLICIT_CONFIG_PATH" ]]; then
        echo "ERROR: --opencode-config requires a path." >&2
        exit 1
      fi
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

to_unix_path() {
  local p="$1"
  if command_exists cygpath; then
    cygpath -u "$p" 2>/dev/null || printf '%s\n' "$p"
  else
    printf '%s\n' "$p"
  fi
}

detect_repo_root() {
  if command_exists git && git rev-parse --show-toplevel >/dev/null 2>&1; then
    git rev-parse --show-toplevel
    return
  fi

  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cd "$script_dir/.." && pwd
}

find_python() {
  if python3 --version >/dev/null 2>&1; then
    PYTHON_CMD=(python3)
    return 0
  fi

  if python --version >/dev/null 2>&1; then
    PYTHON_CMD=(python)
    return 0
  fi

  if py -3 --version >/dev/null 2>&1; then
    PYTHON_CMD=(py -3)
    return 0
  fi

  return 1
}

# Legacy artifacts generated by the previous installer.
LEGACY_AGENTS_HEADER="# Adaptive Agents — OpenCode Global Rules"
LEGACY_COMMAND_FILES=(
  apply-approved-promotion.md
  capture-retrospective.md
  check-adaptive-agents.md
  review-promotion-candidates.md
  review-retrospective-inbox.md
  triage-retrospective.md
)

# ---------------------------------------------------------------------------
# Detect OpenCode config path
# ---------------------------------------------------------------------------

detect_opencode_config_path() {
  if [[ -n "$EXPLICIT_CONFIG_PATH" ]]; then
    to_unix_path "$EXPLICIT_CONFIG_PATH"
    return
  fi

  local opencode_config_env
  opencode_config_env="${OPENCODE_CONFIG:-}"
  if [[ -n "$opencode_config_env" ]]; then
    to_unix_path "$opencode_config_env"
    return
  fi

  # Documented global config location on all platforms:
  # https://opencode.ai/docs/config/ — ~/.config/opencode/opencode.json
  local config_dir="$HOME/.config/opencode"

  # OpenCode supports both .json and .jsonc. Prefer existing file if found.
  if [[ -f "$config_dir/opencode.jsonc" ]]; then
    printf '%s\n' "$config_dir/opencode.jsonc"
  elif [[ -f "$config_dir/opencode.json" ]]; then
    printf '%s\n' "$config_dir/opencode.json"
  else
    printf '%s\n' "$config_dir/opencode.json"
  fi
}

# ---------------------------------------------------------------------------
# Legacy artifact cleanup helpers
# ---------------------------------------------------------------------------

remove_legacy_agents_copy() {
  local agents_path="$1"

  if [[ ! -f "$agents_path" ]]; then
    return 0
  fi

  # Only remove the file the previous installer generated; never delete a
  # user-authored AGENTS.md.
  if [[ "$(sed -n '1p' "$agents_path")" == "$LEGACY_AGENTS_HEADER" ]]; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      echo "[dry-run] Would remove legacy AGENTS.md copy: $agents_path"
    else
      rm "$agents_path"
      echo "Removed legacy AGENTS.md copy: $agents_path"
    fi
  else
    echo "NOTE: $agents_path exists but is not installer-generated; leaving it in place."
  fi
}

remove_legacy_commands() {
  local commands_dir="$1"
  local cmd_name

  if [[ ! -d "$commands_dir" ]]; then
    return 0
  fi

  for cmd_name in "${LEGACY_COMMAND_FILES[@]}"; do
    if [[ -f "$commands_dir/$cmd_name" ]]; then
      if [[ "$DRY_RUN" -eq 1 ]]; then
        echo "[dry-run] Would remove legacy command: $commands_dir/$cmd_name"
      else
        rm "$commands_dir/$cmd_name"
        echo "Removed legacy command: $commands_dir/$cmd_name"
      fi
    fi
  done

  if [[ "$DRY_RUN" -eq 0 ]] && [[ -d "$commands_dir" ]] && [[ -z "$(ls -A "$commands_dir")" ]]; then
    rmdir "$commands_dir"
    echo "Removed empty commands directory: $commands_dir"
  fi
}

cleanup_appdata_artifacts() {
  # The first-generation installer wrote to %APPDATA%/opencode, which OpenCode
  # never consumes (docs list only ~/.config/opencode). Remove our artifacts.
  local appdata="${APPDATA:-}"
  if [[ -z "$appdata" ]]; then
    return 0
  fi

  local appdata_dir
  appdata_dir="$(to_unix_path "$appdata")/opencode"
  if [[ ! -d "$appdata_dir" ]]; then
    return 0
  fi

  local appdata_config="$appdata_dir/opencode.json"
  if [[ -f "$appdata_config" ]]; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      echo "[dry-run] Would remove Adaptive Agents entries from: $appdata_config"
    else
      "${PYTHON_CMD[@]}" - "$appdata_config" "$REPO_ROOT_NORM" <<'PY'
import json
import sys
from pathlib import Path

config_path = Path(sys.argv[1])
repo_root = sys.argv[2]

try:
    config = json.loads(config_path.read_text(encoding="utf-8"))
except (json.JSONDecodeError, OSError):
    raise SystemExit(0)

if not isinstance(config, dict):
    raise SystemExit(0)

changed = False

instructions = config.get("instructions")
if isinstance(instructions, list):
    kept = [e for e in instructions if not (isinstance(e, str) and e.replace("\\", "/").startswith(repo_root))]
    if kept != instructions:
        config["instructions"] = kept
        changed = True
    if not kept:
        del config["instructions"]
        changed = True

if "_adaptive_agents_installed" in config:
    del config["_adaptive_agents_installed"]
    changed = True

if changed:
    if config:
        config_path.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"Removed Adaptive Agents entries from: {config_path}")
    else:
        config_path.unlink()
        print(f"Removed empty legacy config: {config_path}")
PY
    fi
  fi

  remove_legacy_commands "$appdata_dir/commands"

  if [[ "$DRY_RUN" -eq 0 ]] && [[ -d "$appdata_dir" ]] && [[ -z "$(ls -A "$appdata_dir")" ]]; then
    rmdir "$appdata_dir"
    echo "Removed empty legacy directory: $appdata_dir"
  fi
}

# ---------------------------------------------------------------------------
# Main logic
# ---------------------------------------------------------------------------

main() {
  local repo_root
  repo_root="$(detect_repo_root)"

  if [[ ! -f "$repo_root/AGENTS.md" || ! -f "$repo_root/INDEX.md" ]]; then
    echo "ERROR: This does not look like the Adaptive Agents repository root." >&2
    echo "Expected to find AGENTS.md and INDEX.md in: $repo_root" >&2
    exit 1
  fi

  REPO_ROOT_NORM="${repo_root//\\//}"

  local config_path
  config_path="$(detect_opencode_config_path)"
  local config_dir
  config_dir="$(dirname "$config_path")"

  echo "Adaptive Agents repository: $repo_root"
  echo "OpenCode config:            $config_path"

  if command_exists opencode; then
    echo "OpenCode CLI:               $(command -v opencode)"
  else
    echo "OpenCode CLI:               not detected (install from https://opencode.ai)"
  fi
  echo

  if ! find_python; then
    echo "ERROR: Python is required to safely update OpenCode config." >&2
    echo "Install Python, or update $config_path manually:" >&2
    echo "  instructions: add \"$REPO_ROOT_NORM/AGENTS.md\"" >&2
    echo "  permission.external_directory: add \"$REPO_ROOT_NORM/**\": \"allow\"" >&2
    exit 1
  fi

  # -----------------------------------------------------------------------
  # Step 1: Entry point + trust grant in the OpenCode global config
  # -----------------------------------------------------------------------
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] Would create/update: $config_path"
    echo "[dry-run] Would ensure single instructions entry: $REPO_ROOT_NORM/AGENTS.md"
    echo "[dry-run] Would remove legacy instructions entries under: $REPO_ROOT_NORM"
    echo "[dry-run] Would grant permission.external_directory '$REPO_ROOT_NORM/**' = allow"
  else
    mkdir -p "$config_dir"

    "${PYTHON_CMD[@]}" - "$config_path" "$REPO_ROOT_NORM" <<'PY'
import datetime
import json
import shutil
import sys
from pathlib import Path

config_path = Path(sys.argv[1])
repo_root = sys.argv[2]


def strip_jsonc(text: str) -> str:
    """Remove // and /* */ comments while preserving string literals."""
    result = []
    i = 0
    n = len(text)
    in_string = False
    escape = False
    in_line_comment = False
    in_block_comment = False

    while i < n:
        c = text[i]
        nxt = text[i + 1] if i + 1 < n else ""

        if in_line_comment:
            if c in "\r\n":
                in_line_comment = False
                result.append(c)
            i += 1
            continue

        if in_block_comment:
            if c == "*" and nxt == "/":
                in_block_comment = False
                i += 2
            else:
                if c in "\r\n":
                    result.append(c)
                i += 1
            continue

        if in_string:
            result.append(c)
            if escape:
                escape = False
            elif c == "\\":
                escape = True
            elif c == '"':
                in_string = False
            i += 1
            continue

        if c == '"':
            in_string = True
            result.append(c)
            i += 1
            continue

        if c == "/" and nxt == "/":
            in_line_comment = True
            i += 2
            continue

        if c == "/" and nxt == "*":
            in_block_comment = True
            i += 2
            continue

        result.append(c)
        i += 1

    return "".join(result)


def remove_trailing_commas(text: str) -> str:
    """Remove trailing commas before ] or } while preserving string literals."""
    result = []
    i = 0
    n = len(text)
    in_string = False
    escape = False
    while i < n:
        c = text[i]
        if in_string:
            result.append(c)
            if escape:
                escape = False
            elif c == "\\":
                escape = True
            elif c == '"':
                in_string = False
            i += 1
            continue
        if c == '"':
            in_string = True
            result.append(c)
            i += 1
            continue
        if c == ",":
            j = i + 1
            while j < n and text[j].isspace():
                j += 1
            if j < n and text[j] in "}]":
                i += 1
                continue
        result.append(c)
        i += 1
    return "".join(result)


raw = ""
if config_path.exists():
    raw = config_path.read_text(encoding="utf-8")

if raw.strip():
    try:
        config = json.loads(remove_trailing_commas(strip_jsonc(raw)))
    except json.JSONDecodeError:
        print(f"ERROR: could not parse existing config: {config_path}", file=sys.stderr)
        raise SystemExit(1)
else:
    config = {}

if not isinstance(config, dict):
    print(f"ERROR: existing config is not a JSON object: {config_path}", file=sys.stderr)
    raise SystemExit(1)

if "$schema" not in config:
    config["$schema"] = "https://opencode.ai/config.json"

# --- Entry point: exactly one canonical instructions entry -----------------
entry = f"{repo_root}/AGENTS.md"
legacy_entries = {
    f"{repo_root}/INDEX.md",
    f"{repo_root}/instructions/global.instructions.md",
    f"{repo_root}/instructions/*.instructions.md",
}

instructions = config.get("instructions", [])
if not isinstance(instructions, list):
    instructions = [instructions]

merged = []
for item in instructions:
    norm = item.replace("\\", "/") if isinstance(item, str) else item
    if norm in legacy_entries:
        continue  # retired layer: fan-out from AGENTS.md handles routing
    if norm == entry:
        continue  # re-added below, deduplicated
    merged.append(item)
merged.append(entry)
config["instructions"] = merged

# --- Trust grant: repository safe to read/write from external sessions -----
permission = config.get("permission")
if not isinstance(permission, dict):
    permission = {}
external = permission.get("external_directory")
if not isinstance(external, dict):
    external = {} if external is None else {"*": external}
external[f"{repo_root}/**"] = "allow"
permission["external_directory"] = external
config["permission"] = permission

new_content = json.dumps(config, indent=2, ensure_ascii=False) + "\n"

if new_content == raw:
    print(f"OpenCode config already up to date: {config_path}")
else:
    if config_path.exists():
        stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = config_path.with_name(config_path.name + f".adaptive-agents.{stamp}.bak")
        shutil.copy2(config_path, backup)
        print(f"Backup written: {backup}")
    config_path.write_text(new_content, encoding="utf-8")
    print(f"OpenCode config updated: {config_path}")
PY
  fi
  echo

  # -----------------------------------------------------------------------
  # Step 2: Migrate away prior-generation artifacts
  # -----------------------------------------------------------------------
  remove_legacy_agents_copy "$config_dir/AGENTS.md"
  remove_legacy_commands "$config_dir/commands"
  cleanup_appdata_artifacts

  # Refresh the idempotency marker (kept outside the JSON so OpenCode schema
  # validation never sees it).
  local marker_path="$config_dir/.adaptive-agents-installed"
  local marker_content="adaptive-agents-installed $REPO_ROOT_NORM"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] Would write marker: $marker_path"
  elif [[ ! -f "$marker_path" || "$(cat "$marker_path")" != "$marker_content" ]]; then
    printf '%s\n' "$marker_content" > "$marker_path"
    echo "Marker written: $marker_path"
  fi
  echo

  # -----------------------------------------------------------------------
  # Summary
  # -----------------------------------------------------------------------
  echo "Verification (fresh OpenCode session in an unrelated repository):"
  echo "  1. Sentinel:      \"Are Adaptive Agents active?\" -> ADAPTIVE_AGENTS_GLOBAL_LOADED"
  echo "  2. Content proof: \"What is the current active plan and top backlog item?\""
  echo "                    -> must name the actual plan from the repository"
  echo "  3. Write-back:    ask for a retrospective capture -> file appears in"
  echo "                    $REPO_ROOT_NORM/retrospectives/inbox/"
  echo "The sentinel alone is not proof; repeat across multiple fresh sessions."

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo
    echo "[dry-run] No files were modified."
  fi
}

main
