#!/usr/bin/env bash
set -euo pipefail

# Isolated regression tests for scripts/install-vscode.sh.
# All VS Code settings are written under a temporary directory.

PASSES=0
FAILURES=0

pass() {
  PASSES=$((PASSES + 1))
  printf 'PASS: %s\n' "$1"
}

fail() {
  FAILURES=$((FAILURES + 1))
  printf 'FAIL: %s\n' "$1"
}

find_python() {
  if python3 --version >/dev/null 2>&1; then
    PYTHON_CMD=(python3)
  elif python --version >/dev/null 2>&1; then
    PYTHON_CMD=(python)
  elif py -3 --version >/dev/null 2>&1; then
    PYTHON_CMD=(py -3)
  else
    return 1
  fi
}

REPO_ROOT="$(git rev-parse --show-toplevel)"
REPO_ROOT_NORM="${REPO_ROOT//\\//}"
INSTALLER="$REPO_ROOT/scripts/install-vscode.sh"

if ! find_python; then
  echo "ERROR: Python is required to run these tests." >&2
  exit 1
fi

TMP_ROOT="$(mktemp -d)"
trap 'rm -rf "$TMP_ROOT"' EXIT

run_installer() {
  local settings_path="$1"
  shift
  bash "$INSTALLER" --settings "$settings_path" "$@"
}

json_check() {
  local settings_path="$1"
  local expression="$2"
  "${PYTHON_CMD[@]}" - "$settings_path" "$REPO_ROOT_NORM" <<PY
import json
import sys

settings = json.load(open(sys.argv[1], encoding="utf-8"))
repo = sys.argv[2]
raise SystemExit(0 if ($expression) else 1)
PY
}

# Fresh install writes the exact public Copilot setting consumed by read_file.
T1="$TMP_ROOT/fresh/settings.json"
run_installer "$T1" >/dev/null
if json_check "$T1" 'settings.get("github.copilot.chat.additionalReadAccessPaths") == [repo]'; then
  pass "fresh install writes additionalReadAccessPaths"
else
  fail "fresh install writes additionalReadAccessPaths"
fi

# Migrate the ineffective key generated by the first implementation.
T2="$TMP_ROOT/migration/settings.json"
mkdir -p "$(dirname "$T2")"
cat > "$T2" <<EOF
{
  // Existing unrelated settings and valid paths must survive JSONC parsing.
  "editor.fontSize": 15,
  "github.copilot.chat.additionalReadAccessFolders": ["$REPO_ROOT_NORM"],
  "github.copilot.chat.additionalReadAccessPaths": ["C:/existing/read/path"],
}
EOF
run_installer "$T2" >/dev/null
if json_check "$T2" '"github.copilot.chat.additionalReadAccessFolders" not in settings and settings.get("github.copilot.chat.additionalReadAccessPaths") == ["C:/existing/read/path", repo]'; then
  pass "JSONC migration removes obsolete key and preserves valid paths"
else
  fail "JSONC migration removes obsolete key and preserves valid paths"
fi
if json_check "$T2" 'settings.get("editor.fontSize") == 15'; then
  pass "migration preserves unrelated settings"
else
  fail "migration preserves unrelated settings"
fi

# Rerunning does not duplicate the path or change settings content.
BEFORE="$TMP_ROOT/before.json"
cp "$T1" "$BEFORE"
run_installer "$T1" >/dev/null
if cmp -s "$BEFORE" "$T1" && json_check "$T1" 'settings.get("github.copilot.chat.additionalReadAccessPaths", []).count(repo) == 1'; then
  pass "rerun is byte-stable and does not duplicate the path"
else
  fail "rerun is byte-stable and does not duplicate the path"
fi

# Dry-run leaves an existing settings file untouched.
T4="$TMP_ROOT/dry-run/settings.json"
mkdir -p "$(dirname "$T4")"
printf '{"editor.wordWrap":"on"}\n' > "$T4"
cp "$T4" "$TMP_ROOT/dry-run-before.json"
run_installer "$T4" --dry-run >/dev/null
if cmp -s "$TMP_ROOT/dry-run-before.json" "$T4"; then
  pass "dry-run does not modify settings"
else
  fail "dry-run does not modify settings"
fi

printf '\nVS Code installer tests: %d passed, %d failure(s).\n' "$PASSES" "$FAILURES"
[[ "$FAILURES" -eq 0 ]]
