#!/usr/bin/env bash
set -euo pipefail

# Isolated regression tests for scripts/install-vscode.sh.
# All VS Code settings are written under a temporary directory.

PASSES=0
FAILURES=0

pass() {
  PASSES=$((PASSES + 1))
  printf 'PASS: %s\n' "$1"
}

fail() {
  FAILURES=$((FAILURES + 1))
  printf 'FAIL: %s\n' "$1"
}

find_python() {
  if python3 --version >/dev/null 2>&1; then
    PYTHON_CMD=(python3)
  elif python --version >/dev/null 2>&1; then
    PYTHON_CMD=(python)
  elif py -3 --version >/dev/null 2>&1; then
    PYTHON_CMD=(py -3)
  else
    return 1
  fi
}

REPO_ROOT="$(git rev-parse --show-toplevel)"
REPO_ROOT_NORM="${REPO_ROOT//\\//}"
INSTALLER="$REPO_ROOT/scripts/install-vscode.sh"

if ! find_python; then
  echo "ERROR: Python is required to run these tests." >&2
  exit 1
fi

TMP_ROOT="$(mktemp -d)"
trap 'rm -rf "$TMP_ROOT"' EXIT

run_installer() {
  local settings_path="$1"
  shift
  bash "$INSTALLER" --settings "$settings_path" "$@"
}

json_check() {
  local settings_path="$1"
  local expression="$2"
  local expected_repo="${3:-$REPO_ROOT_NORM}"
  "${PYTHON_CMD[@]}" - "$settings_path" "$expected_repo" <<PY
import json
import re
import sys

settings = json.load(open(sys.argv[1], encoding="utf-8"))
repo = sys.argv[2]
raise SystemExit(0 if ($expression) else 1)
PY
}

# Fresh install writes the exact public Copilot setting consumed by read_file.
T1="$TMP_ROOT/fresh/settings.json"
T1_OUTPUT="$(run_installer "$T1")"
if json_check "$T1" 'settings.get("github.copilot.chat.additionalReadAccessPaths") == [repo]'; then
  pass "fresh install writes additionalReadAccessPaths"
else
  fail "fresh install writes additionalReadAccessPaths"
fi

if json_check "$T1" 'any(value == {"approve": True, "matchCommandLine": True} and re.fullmatch(key[1:-1], f"bash {chr(34)}{repo}/scripts/session-start.sh{chr(34)}") for key, value in settings.get("chat.tools.terminal.autoApprove", {}).items() if key.startswith("/") and key.endswith("/"))'; then
  pass "fresh install approves the exact session-start command line"
else
  fail "fresh install approves the exact session-start command line"
fi

if json_check "$T1" 'all(not re.fullmatch(key[1:-1], f"bash {chr(34)}{repo}/scripts/session-start.sh{chr(34)} --extra") for key, value in settings.get("chat.tools.terminal.autoApprove", {}).items() if value == {"approve": True, "matchCommandLine": True} and key.startswith("/") and key.endswith("/"))'; then
  pass "session-start approval does not match command-line suffixes"
else
  fail "session-start approval does not match command-line suffixes"
fi
if [[ "$T1_OUTPUT" == *"chat.tools.terminal.autoApprove + exact session-start command"* ]]; then
  pass "completion summary reports the terminal approval"
else
  fail "completion summary reports the terminal approval"
fi
if grep -Fq "Before responding to the first user request, run \`bash \"$REPO_ROOT_NORM/scripts/session-start.sh\"\`" "$REPO_ROOT/vscode/user-wide.instructions.md"; then
  pass "bootstrap requires the exact session-start command before first response"
else
  fail "bootstrap requires the exact session-start command before first response"
fi

# Migrate the ineffective key generated by the first implementation.
T2="$TMP_ROOT/migration/settings.json"
mkdir -p "$(dirname "$T2")"
cat > "$T2" <<EOF
{
  // Existing unrelated settings and valid paths must survive JSONC parsing.
  "editor.fontSize": 15,
  "github.copilot.chat.additionalReadAccessFolders": ["$REPO_ROOT_NORM"],
  "github.copilot.chat.additionalReadAccessPaths": ["C:/existing/read/path"],
  "chat.tools.terminal.autoApprove": {
    "git status": true,
    "rm": false,
    "/^bash\\\\ \"C:/old/adaptive-agents/scripts/session\\\\-start\\\\.sh\"$/": {
      "approve": true,
      "matchCommandLine": true
    },
    "/^existing exact command$/": {
      "approve": true,
      "matchCommandLine": true
    }
  },
}
EOF
run_installer "$T2" >/dev/null
if json_check "$T2" '"github.copilot.chat.additionalReadAccessFolders" not in settings and settings.get("github.copilot.chat.additionalReadAccessPaths") == ["C:/existing/read/path", repo]'; then
  pass "JSONC migration removes obsolete key and preserves valid paths"
else
  fail "JSONC migration removes obsolete key and preserves valid paths"
fi
if json_check "$T2" 'settings.get("editor.fontSize") == 15'; then
  pass "migration preserves unrelated settings"
else
  fail "migration preserves unrelated settings"
fi
if json_check "$T2" 'settings.get("chat.tools.terminal.autoApprove", {}).get("git status") is True and settings.get("chat.tools.terminal.autoApprove", {}).get("rm") is False and settings.get("chat.tools.terminal.autoApprove", {}).get("/^existing exact command$/") == {"approve": True, "matchCommandLine": True}'; then
  pass "migration preserves existing terminal approval and deny rules"
else
  fail "migration preserves existing terminal approval and deny rules"
fi
if json_check "$T2" 'all("C:/old/adaptive-agents/scripts/session" not in key for key in settings.get("chat.tools.terminal.autoApprove", {}))'; then
  pass "migration removes stale Adaptive Agents session-start approval"
else
  fail "migration removes stale Adaptive Agents session-start approval"
fi

# Rerunning does not duplicate the path or change settings content.
BEFORE="$TMP_ROOT/before.json"
cp "$T1" "$BEFORE"
run_installer "$T1" >/dev/null
if cmp -s "$BEFORE" "$T1" && json_check "$T1" 'settings.get("github.copilot.chat.additionalReadAccessPaths", []).count(repo) == 1'; then
  pass "rerun is byte-stable and does not duplicate the path"
else
  fail "rerun is byte-stable and does not duplicate the path"
fi

# Dry-run leaves an existing settings file untouched.
T4="$TMP_ROOT/dry-run/settings.json"
mkdir -p "$(dirname "$T4")"
printf '{"editor.wordWrap":"on"}\n' > "$T4"
cp "$T4" "$TMP_ROOT/dry-run-before.json"
run_installer "$T4" --dry-run >/dev/null
if cmp -s "$TMP_ROOT/dry-run-before.json" "$T4"; then
  pass "dry-run does not modify settings"
else
  fail "dry-run does not modify settings"
fi

# A malformed approval setting fails explicitly without changing the file.
T5="$TMP_ROOT/malformed/settings.json"
mkdir -p "$(dirname "$T5")"
printf '{"chat.tools.terminal.autoApprove":true}\n' > "$T5"
cp "$T5" "$TMP_ROOT/malformed-before.json"
if run_installer "$T5" >/dev/null 2>&1; then
  fail "non-object terminal approvals are rejected"
elif cmp -s "$TMP_ROOT/malformed-before.json" "$T5"; then
  pass "non-object terminal approvals are rejected without modification"
else
  fail "non-object terminal approvals are rejected without modification"
fi

# The installer derives its repository from its own path, not the caller's repo.
T6="$TMP_ROOT/unrelated/settings.json"
mkdir -p "$TMP_ROOT/unrelated/repo"
git -C "$TMP_ROOT/unrelated/repo" init -q
if (cd "$TMP_ROOT/unrelated/repo" && bash "$INSTALLER" --settings "$T6" >/dev/null) && json_check "$T6" 'settings.get("github.copilot.chat.additionalReadAccessPaths") == [repo]'; then
  pass "installer is independent of the caller working directory"
else
  fail "installer is independent of the caller working directory"
fi

# Regex metacharacters in the repository path remain literal command text.
SPECIAL_REPO="$TMP_ROOT/repo.with+chars"
mkdir -p "$SPECIAL_REPO/scripts"
cp "$INSTALLER" "$SPECIAL_REPO/scripts/install-vscode.sh"
touch "$SPECIAL_REPO/AGENTS.md" "$SPECIAL_REPO/INDEX.md"
T7="$TMP_ROOT/special/settings.json"
bash "$SPECIAL_REPO/scripts/install-vscode.sh" --settings "$T7" >/dev/null
SPECIAL_REPO_NORM="$(cygpath -m "$SPECIAL_REPO" 2>/dev/null || printf '%s' "$SPECIAL_REPO")"
if json_check "$T7" 'any(re.fullmatch(key[1:-1], f"bash {chr(34)}{repo}/scripts/session-start.sh{chr(34)}") for key, value in settings.get("chat.tools.terminal.autoApprove", {}).items() if value == {"approve": True, "matchCommandLine": True} and key.startswith("/") and key.endswith("/"))' "$SPECIAL_REPO_NORM"; then
  pass "repository regex metacharacters are matched literally"
else
  fail "repository regex metacharacters are matched literally"
fi

printf '\nVS Code installer tests: %d passed, %d failure(s).\n' "$PASSES" "$FAILURES"
[[ "$FAILURES" -eq 0 ]]
